FROM public.ecr.aws/lambda/python:3.11

WORKDIR ${LAMBDA_TASK_ROOT}

COPY lambdas/url_discovery_handler/requirements.lambda.txt ./requirements.lambda.txt
RUN pip install --no-cache-dir -r requirements.lambda.txt

COPY lambdas/url_discovery_handler/lambda_function.py ./lambda_function.py

CMD ["lambda_function.lambda_handler"]
